export default {
  accessInput: document.getElementById('keyword'),
  accessUl: document.querySelector('.newAnchors'),
  accessSelectedWebsite: document.getElementById('website').value,
  accessScrollUp: document.querySelector('.scrollup'),
  accessGenerateButton: document.querySelector('.button__generate'),
  keywords: [
    'write my research papers',
    'pay someone to write my research paper',
    'research paper writing help',
    'write my research paper for me',
    'do my research paper',
    'order research paper',
    'write a research paper for me',
    'pay for research paper',
    'research paper writing service',
    'research paper writer',
    'research paper writers',
    'online research paper writer',
    'do my research paper for me',
  ],
  brandName: [
    'EssayPro',
    'at EssayPro',
    'from EssayPro',
    'by EssayPro',
    'to EssayPro',
    'with EssayPro',
  ],
  lsiWords: [
    'writer',
    'customer',
    'stars',
    'essay',
    'paper',
    'writing',
    'writing-service',
    'proofreading-service',
    'work',
    'editing-service',
    'review',
    'service',
    'good',
    'time',
    'deadline',
    'research',
    'assignment',
    'read',
    'order',
    'write',
    'sample',
    'report',
    'business',
    'great',
    'free',
    'academic',
    'needed',
    'writers',
    'case',
    'job',
    'need',
    'study',
    'support',
    'type',
    'excellent',
    'revisions',
    'completed',
    'ask',
    'asked',
    'hire',
    'days',
    'quality',
    'term',
    'presentation',
    'proofread',
    'provide',
    'requirements',
    'reviews',
    'book',
    'admission',
    'speech',
    'plagiarism',
    'papers',
    'request',
    'instructions',
    'movie',
    'thinking',
    'critical',
    'article',
    'finance',
    'questions',
    'thesis',
    'bibliography',
    'annotated',
    'received',
    'team',
    'information',
    'professional',
    'creative',
    'reflective',
    'plan',
    'recommend',
    'fast',
    'proposal',
    'literature',
    'highly',
    'rate',
    'orders',
    'finished',
    'expert',
    'personal',
    'experience',
    'due',
    'written',
    "don't",
    'unlimited',
    'contact',
    'success',
    'submitted',
    'customers',
    'complete',
    'issues',
    'chat',
    'edited',
    'place',
    'simply',
    'find',
    'students',
    'deliver',
    'choose',
    'delivered',
    'editing',
    'late',
    'edit',
    'assignments',
    'formatting',
    'pages',
    'services',
    'page',
    'expected',
    'bit',
    'amazing',
    'price',
    'pay',
    'give',
    'add',
    'title',
    'easy',
    'details',
    'date',
    'rating',
    'minutes',
    'hours',
    'attention',
    'timely',
    'follow',
    'hour',
    'grade',
    'gave',
    "didn't",
    'send',
    'high',
    'day',
    'completely',
    'process',
    "it's",
    "master's",
    'revise',
    'raymond',
    'awesome',
    'extra',
    'pick',
    'policy',
    'final',
    'original',
    'satisfaction',
    'receive',
    'specialist',
    'guarantee',
    'task',
    'put',
    'quickly',
    'form',
    'account',
    'detail',
    'fixed',
    'short',
    'charles',
    'typos',
    "wasn't",
    'edits',
    'directions',
    'early',
    'user',
    'competences',
    'degree',
    'college',
    'email',
    'happy',
    "we'll",
    'set',
    'click',
    'hiring',
    'touch',
    'content',
    'including',
    'hired',
    'offer',
    'satisfactorily',
    'reference',
    'style',
    'amount',
    'ensure',
    'based',
    'files',
    'affordable',
    'choice',
    'tight',
    'perfect',
    'skills',
    'quick',
    'skipped',
    'times',
    'errors',
    'top',
    'reach',
    'editor',
    'essays',
    'data',
    'payment',
    'share',
    'feel',
    'main',
    'number',
    'check',
    'scratch',
    'matter',
    'initial',
    'level',
    'text',
    "you'll",
    'completion',
    'lot',
    'specialists',
    'online',
    'result',
    'hundreds',
    'download',
    'left',
    'deadlines',
    'delivery',
    'feedback',
    'professionalism',
    'answer',
    'close',
    'helped',
    'features',
    'proofreading',
    'next',
    'felt',
    'communication',
    'accurate',
    'slides',
    'redo',
    'pretty',
    'efficient',
    'point',
    'future',
    'Turnitin',
    'manner',
    'negotiable',
    'experts',
    'buy',
    'strictly',
    'privacy',
    'important',
    'today',
    'tasks',
    'code',
    'security',
    'secure',
    'extremely',
    'client',
    'part',
    'software',
    'standards',
    'originality',
    'respond',
    'funds',
    'progress',
    'money',
    "here's",
    'qualified',
    'happily',
    'referencing',
    'resolved',
    'changed',
    'entire',
    'outline',
    'required',
    'select',
    'start',
    'strive',
    'upload',
    'view',
    'straight',
    'comments',
    'description',
    'levels',
    'nice',
    'helpers',
    'home',
    'exam',
    'confidentiality',
    'safety',
    'homeworks',
    'wait',
    'site',
    'student',
    'custom',
    'grades',
    'unique',
    'complexity',
    'topic',
    'handle',
    'payments',
    'performance',
    'areas',
    'prices',
    'anonymity',
    'helpful',
    'person',
    'charges',
    'hidden',
    'blog',
    'rewrite',
    'assistance',
    'subjects',
    'works',
    'polish',
    'discipline',
    'leave',
    'top-level',
    'topics',
    'school',
    'trusted',
    'solve',
    'lots',
    'improve',
    'line',
    'drop',
    'gateways',
    'secured',
    'advanced',
    'core',
    'clients',
    'pros',
    'high-quality',
    'confirm',
    'professor',
    'Ph.D.',
    'handled',
    'satisfied',
    'release',
    'authors',
    "bachelor's",
    'education',
    'providing',
    'plagiarism-free',
    'assured',
    'rest',
    'pocket-friendly',
    'included',
    'Vancouver',
    'Chicago',
    'Turabian',
    'Harvard',
    'MLA',
    'APA',
    'suitable',
    'steps',
    'acquiring',
    'phase',
    'totally',
    'organized',
    'save',
    'people',
    'multiple',
    'fantastic',
    'working',
    'sitejabber',
    'year',
    'psychology',
    'humanities',
    'arts',
    'liberal',
    'Keyword',
    'read sample',
    'sample read',
    'physics homework',
    'physics help',
    'thesis dissertation',
    'customer id',
    'homework help',
    'on time',
    'help service',
    'physic homework',
    'this writer',
    'our service',
    'order physics',
    "master's degree",
    'hire writer',
    'homework user',
    'writer physics',
    'review about',
    'recent review',
    'degree competences',
    'finished orders',
    'success rate',
    'at Essaypro',
    'you need',
    'an order',
    'our physics',
    'Turnitin report',
    'free Turnitin',
    'love the',
    'i love',
    "orders master's",
    'my essay',
    'place an',
    'your physics',
    'time to',
    'your academic',
    'you order',
    'my physics',
    'the work',
    'the order',
    'with physics',
    'writer and',
    'easy to',
    'paper writing',
    'would recommend',
    'essay help',
    'college essay',
    'service and',
    'based on',
    'and complexity',
    'need to',
    'timely delivery',
    'support team',
    'privacy and',
    'your privacy',
    'to work',
    'a physics',
    'any questions',
    'quality and',
    'I need',
    'to choose',
    'the payment',
    'i needed',
    'helpful in',
    'helped me',
    'the writer',
    'I feel',
    'was great',
    'my thesis',
    'an excellent',
    'my writer',
    'revisions to',
    'unlimited revisions',
    'hidden charges',
    'no hidden',
    'every student',
    'homework on',
    'rewrite my',
    'dissertation writing',
    'custom writing',
    'type of',
    'research and',
    'service is',
    'contact us',
    'a writer',
    'deadlines and',
    'EssayPro and',
    'proofreading and',
    'polish your',
    'you polish',
    'unique requirements',
    'your unique',
    'assignment or',
    'of homework',
    'can handle',
    'physic helper',
    'students can',
    'physics and',
    'EssayPro is',
    'delivery and',
    'zero plagiarism',
    'you place',
    'complexity levels',
    'academic levels',
    'all academic',
    'service you',
    'service that',
    'time we',
    'issues and',
    'to solve',
    'lots of',
    'to improve',
    'the next',
    'more time',
    'a line',
    'our support',
    'and confidentiality',
    'safety and',
    'secured gateways',
    'through secured',
    'all payments',
    'personal information',
    'our clients',
    'the top',
    'academic performance',
    'receive a',
    'you receive',
    'work on',
    'to confirm',
    'an exam',
    'level of',
    'helper with',
    'homework helper',
    'hire a',
    'with physic',
    'pay for',
    'for revisions',
    'issues with',
    'chat with',
    'questions or',
    'the result',
    'satisfied with',
    'the money',
    'release the',
    'and release',
    'the quality',
    'check the',
    'can check',
    'the assignment',
    'time for',
    'our authors',
    'delivered on',
    'degree and',
    "bachelor's degree",
    'in providing',
    'a free',
    'work help',
    'rest assured',
    'guarantee that',
    'your paper',
    'physics helper',
    'most suitable',
    'that helped',
  ],
  // lsiWords: [
  //   '100 success',
  //   '2020 writer',
  //   'a bad',
  //   'a job',
  //   'a lot',
  //   'a master’s',
  //   'a paper',
  //   'a professional',
  //   'a specific',
  //   'a writer',
  //   'ability',
  //   'ability to',
  //   'academic',
  //   'academic paper',
  //   'academic performance',
  //   'account',
  //   'active',
  //   'active promo',
  //   'affordable',
  //   'an essay',
  //   'an exam',
  //   'an order',
  //   'assignment',
  //   'assignments',
  //   'bad',
  //   'based',
  //   'based on',
  //   'best paper',
  //   'budget',
  //   'can write',
  //   'care',
  //   'care to',
  //   'catalog',
  //   'caught',
  //   'caught using',
  //   'chat',
  //   'chat and',
  //   'cheap',
  //   'check',
  //   'choice',
  //   'choose',
  //   'choose a',
  //   'client',
  //   'clients',
  //   'codes',
  //   'college',
  //   'company',
  //   'completed',
  //   'completed 100',
  //   'completing',
  //   'complexity',
  //   'customer',
  //   'customer and',
  //   'customer support',
  //   'day',
  //   'deadline',
  //   'deadline for',
  //   'deadline is',
  //   'deadlines',
  //   'degree',
  //   'degree or',
  //   'degrees',
  //   'deposit',
  //   'details',
  //   'discount',
  //   'double-deadline',
  //   'draft',
  //   'eager',
  //   'easily',
  //   'easy',
  //   'easy-to-use',
  //   'edit',
  //   'edit the',
  //   'editing',
  //   'edits',
  //   'email',
  //   'enjoy',
  //   'ensure',
  //   'ensure that',
  //   'essay',
  //   'essay and',
  //   'essays',
  //   'essays can',
  //   'every paper',
  //   'every student',
  //   'exam',
  //   'experience',
  //   'experience in',
  //   'experience was',
  //   'expertise',
  //   'extra',
  //   'fast',
  //   'features',
  //   'field',
  //   'fields',
  //   'fields of',
  //   'final',
  //   'find',
  //   'find a',
  //   'find someone',
  //   'finding',
  //   'finding a',
  //   'flawless',
  //   'follow',
  //   'for free',
  //   'for important',
  //   'for students',
  //   'form',
  //   'formatting',
  //   'free',
  //   'full',
  //   'fully',
  //   'funds',
  //   'get caught',
  //   'give',
  //   'give us',
  //   'give you',
  //   'grade',
  //   'great',
  //   'great care',
  //   'guarantee',
  //   'guide',
  //   'guide you',
  //   'hannah',
  //   'hannah taylor',
  //   'happy',
  //   'happy to',
  //   'hear',
  //   'hear from',
  //   'help write',
  //   'helpful',
  //   'helping',
  //   'high',
  //   'high-quality',
  //   'higher',
  //   'hire',
  //   'hire a',
  //   'homework',
  //   'hours',
  //   'i pay',
  //   'impact',
  //   'important',
  //   'in order',
  //   'included',
  //   'included in',
  //   'information',
  //   'interface',
  //   'is completed',
  //   'job',
  //   'keyword',
  //   'kind',
  //   'kind of',
  //   'learn',
  //   'level',
  //   'library',
  //   'life',
  //   'list',
  //   'list of',
  //   'long',
  //   'lot',
  //   'lots',
  //   'lots of',
  //   'making',
  //   'master’s',
  //   'me request',
  //   'me write',
  //   'mitchell',
  //   'money',
  //   'my experience',
  //   'my paper',
  //   'my papers',
  //   'need',
  //   'of experience',
  //   'of expertise',
  //   'of paper',
  //   'of students',
  //   'of time',
  //   'of writers',
  //   'offer',
  //   'on time',
  //   'online',
  //   'online who',
  //   'open',
  //   'option',
  //   'order',
  //   'order is',
  //   'orders',
  //   'orders completed',
  //   'our clients',
  //   'our paper',
  //   'our team',
  //   'our website',
  //   'our writers',
  //   'page',
  //   'page free',
  //   'paper before',
  //   'paper fast',
  //   'paper for',
  //   'paper help',
  //   'paper is',
  //   'paper on',
  //   'paper pay',
  //   'paper request',
  //   'paper writer',
  //   'paper writers',
  //   'paper writing',
  //   'paper you',
  //   'papers',
  //   'papers and',
  //   'papers for',
  //   'pay',
  //   'pay someone',
  //   'payments',
  //   'pen',
  //   'people',
  //   'people who',
  //   'per page',
  //   'performance',
  //   'person',
  //   'personal',
  //   'ph.d',
  //   'philip',
  //   'philip a',
  //   'picking',
  //   'picking a',
  //   'place',
  //   'plagiarism',
  //   'policy',
  //   'pretty',
  //   'price',
  //   'priority',
  //   'privacy and',
  //   'process',
  //   'prof',
  //   'prof philip',
  //   'professional',
  //   'professional paper',
  //   'professionals',
  //   'professor',
  //   'profiles',
  //   'promo',
  //   'promo codes',
  //   'proof',
  //   'proof of',
  //   'provide',
  //   'provide you',
  //   'quality',
  //   'question',
  //   'questions',
  //   'rate',
  //   'rate hire',
  //   'rating',
  //   'read',
  //   'ready',
  //   'ready to',
  //   'real',
  //   'receive',
  //   'received',
  //   'recommend',
  //   'reliable',
  //   'report',
  //   'request',
  //   'request and',
  //   'requirements',
  //   'research',
  //   'reviews',
  //   'revise',
  //   'ryan',
  //   'ryan mitchell',
  //   'save',
  //   'search',
  //   'secured',
  //   'select',
  //   'send',
  //   'send us',
  //   'send you',
  //   'service customer',
  //   'service in',
  //   'service is',
  //   'services',
  //   'set',
  //   'simple',
  //   'simple and',
  //   'sitting',
  //   'social',
  //   'solve',
  //   'someone write',
  //   'sources',
  //   'specific',
  //   'start',
  //   'start working',
  //   'student',
  //   'students',
  //   'students and',
  //   'students who',
  //   'study',
  //   'style',
  //   'subject',
  //   'success',
  //   'success rate',
  //   'super',
  //   'support',
  //   'support team',
  //   'system',
  //   'tackle',
  //   'take great',
  //   'taylor',
  //   'team',
  //   'team will',
  //   'term',
  //   'terms',
  //   'tests',
  //   'the ability',
  //   'the chat',
  //   'the deadline',
  //   'the final',
  //   'the library',
  //   'the order',
  //   'the paper',
  //   'the search',
  //   'the writer',
  //   'their gpa',
  //   'their work',
  //   'this service',
  //   'time',
  //   'time in',
  //   'time to',
  //   'to ensure',
  //   'to find',
  //   'to guide',
  //   'to learn',
  //   'to provide',
  //   'to write',
  //   'turn',
  //   'turn to',
  //   'tutor',
  //   'tutor ryan',
  //   'type',
  //   'types',
  //   'types of',
  //   'up time',
  //   'waiting',
  //   'waiting to',
  //   'was pretty',
  //   'website',
  //   'work',
  //   'work and',
  //   'work in',
  //   'work on',
  //   'work with',
  //   'working',
  //   'working on',
  //   'working with',
  //   'worry',
  //   'worry about',
  //   'write a',
  //   'write my',
  //   'WritePaper',
  //   'WritePaper is',
  //   'writer can',
  //   'writer hannah',
  //   'writer is',
  //   'writer prof',
  //   'writer to',
  //   'writer tutor',
  //   'writers',
  //   'writers are',
  //   'writing a',
  //   'writing help',
  //   'writing service',
  //   'written',
  //   'written by',
  //   'written papers',
  //   'you need',
  //   'your academic',
  //   'your account',
  //   'your assignment',
  //   'your essay',
  //   'your order',
  //   'your paper',
  //   'your professor',
  //   'your work',
  //   'your write',
  // ],
};
